Task1: add price increase scheduling
NikitinNikita94/wareshop pull request #3
Opened 2024-04-16 13:15 UTC by NikitinNikita94

a) - простой и оптимизированный
- в профиле Local не создаются никогда
- шедулеры не создаются если app.scheduling.enabled=false
- простой создается, если не создан оптимизированный и app.scheduling.enabled=true
- оптимизированный шедулер создается если scheduling.optimization=true (и выполнились предыдущие условия)
- 1М записей в БД
- простой шедулер: findAll, меняет цену в стриме, saveAll + Transactional
- попробовать локи pessimistickLock, optimistick

- сложный шедулер
- уложиться в 1 минуту, 500Мб (контроль в visualVm)
- запись в файл
- exclusive lock и select for update

б) - своя аннотация которая замеряет время работы метода
   - advice который замеряет время trasnactional

2024-04-21 18:18 UTC, GUR-ok commented
Давай назовем мр "Task1: add price increase scheduling" а не "Home work/task1". именно с таким комментарием в итоге смержится сквошнутый коммит в девелоп

2024-04-21 18:31 UTC, GUR-ok requested changes

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/aop/MarkTimeExecutionAspect.java
> +        Object result = joinPoint.proceed();
Если joinPoint.proceed(); бросит исключение время замереется?
Мб try {
            return joinPoint.proceed();
        } finally {
			вывести время

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/aop/TransactionExecutionAspect.java
> +        startTime.set(System.nanoTime());
старт таймера начинается от начала работы тела метода или от начала коммита транзакции?

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/aop/TransactionExecutionAspect.java
> +
Такие пустые строки лучше убирать

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/entity/Product.java
> +@Data
Data вроде наоборот говорил убирать

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/scheduler/OptimizedProductScheduler.java
> +@ConditionalOnProperty(prefix = "app.scheduling", name = "enabled", havingValue = "true")
А можем объединить в одно условие? @ConditionalOnExpression("${app.scheduling.optimization} && ${app.scheduling.enabled}") плюс нужно добавить дефолтные false на случай отсутствия конфига типа так ...${app.scheduling.optimization:false}...

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/scheduler/OptimizedProductScheduler.java
> +        List<Product> allProducts = findAllProducts().stream()
А в чем тут оптимизированность? в задании лимит 500Мб памяти. миллион объектов загрузится в память. приложи скрин visualVm плз

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/scheduler/OrdinaryProductScheduler.java
> +                .peek(product -> product.setPrice(product.getPrice().add(price)))
черек пик не принято модифицировать объекты.  давай map

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/scheduler/OrdinaryProductScheduler.java
> +                .peek(product -> product.setPrice(product.getPrice().add(price)))
почему .add(price)? нам нужно увеличивать на процент же, а не прибавлять?

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/scheduler/OrdinaryProductScheduler.java
> +@ConditionalOnProperty(prefix = "app.scheduling", name = "enabled", havingValue = "true")
тут тоже объединить два условия в одно тогда

2024-04-21 18:31 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/scheduler/OrdinaryProductScheduler.java
> +@Profile("dev")
dev и !local это разные вещи. а если появится production? по заданию там "не local"

2024-04-24 10:48 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/aop/TransactionExecutionAspect.java
> +        startTime.set(System.nanoTime());
От начала коммита транзакции.

2024-04-24 10:50 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/scheduler/OptimizedProductScheduler.java
> +        List<Product> allProducts = findAllProducts().stream()
К сожалению если я одновременно юзаю IDE и visualVm у меня либо зависает все,либо просто вылетает с IDE!

2024-04-24 10:50 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/scheduler/OrdinaryProductScheduler.java
> +                .peek(product -> product.setPrice(product.getPrice().add(price)))
Моя невнимательность,прошу прощенья,исправлю.

2024-04-25 13:25 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/aop/TransactionExecutionAspect.java
> +        startTime.set(System.nanoTime());
хотелось бы от начала тела метода до конца коммита транзакции

2024-04-25 13:27 UTC, GUR-ok commented
кавычки не нужны в названии мр )

2024-04-25 13:28 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/scheduler/OptimizedProductScheduler.java
> +        List<Product> allProducts = findAllProducts().stream()
Включи в мр плз тогда текст самого оптимального шедулера, чтобы осталось на будущее

package com.crudshop.demo.scheduling;

import com.crudshop.demo.annotation.MeasureExecutionTime;
import jakarta.persistence.EntityManagerFactory;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.Session;
import org.hibernate.jdbc.Work;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnExpression;
import org.springframework.context.annotation.Profile;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

@Component
@Profile("!local")
@ConditionalOnExpression(value = "#{'${app.scheduling.mode:none}'.equals('super')}")
@Slf4j
public class SuperOptimizedScheduler {

    private static final String QUERY = "UPDATE products SET price = price * (1 + ?/100) RETURNING *";

    private final BigDecimal priceIncreasePercentage;

    private final EntityManagerFactory entityManagerFactory;

    public SuperOptimizedScheduler(
            @Value("#{new java.math.BigDecimal(\"${app.scheduling.priceIncreasePercentage:10}\")}")
            BigDecimal priceIncreasePercentage,
            EntityManagerFactory entityManagerFactory
    ) {
        this.priceIncreasePercentage = priceIncreasePercentage;
        this.entityManagerFactory = entityManagerFactory;
    }

    @MeasureExecutionTime
    @Scheduled(fixedDelayString = "${app.scheduling.period}")
    public void increaseProductPrice() {
        log.info("Start SUPER OptimizedProductPriceScheduler");

        final Session session = entityManagerFactory.createEntityManager().unwrap(Session.class);
        try (session) {
            session.doWork(new Work() {
                @Override
                public void execute(final Connection connection) throws SQLException {
                    try (
                            final BufferedWriter fileWriter = new BufferedWriter(new FileWriter("results.txt"));
                            connection
                    ) {
                        connection.setAutoCommit(false);
                        final PreparedStatement preparedStatement = connection.prepareStatement(QUERY);
                        preparedStatement.setBigDecimal(1, priceIncreasePercentage);

                        final ResultSet resultSet = preparedStatement.executeQuery();
                        while (resultSet.next()) {
                            fileWriter.write(buildString(resultSet));
                        }

                        connection.commit();
                    } catch (Exception e) {
                        connection.rollback();
                        throw new RuntimeException(e);
                    }
                }
            });
        }

        log.info("End Super OptimizedProductPriceScheduler");
    }

    private String buildString(final ResultSet resultSet) throws SQLException {
        final StringBuilder builder = new StringBuilder();
        builder.append(resultSet.getString("id"));
        builder.append(" ");
        builder.append(resultSet.getString("name"));
        builder.append(" ");
        builder.append(resultSet.getString("description"));
        builder.append(" ");
        builder.append(resultSet.getString("price"));
        builder.append(" ");
        builder.append(resultSet.getString("article"));

        return builder.toString();
    }
}

2024-04-25 13:29 UTC, GUR-ok commented
кинь мне инвайт на котрибьютера плз

2024-04-25 13:30 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/scheduler/OptimizedProductScheduler.java
> +        List<Product> allProducts = findAllProducts().stream()
или этот
```
package com.crudshop.demo.scheduling;

import com.crudshop.demo.annotation.MeasureExecutionTime;
import jakarta.persistence.EntityManagerFactory;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.Session;
import org.hibernate.jdbc.Work;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnExpression;
import org.springframework.context.annotation.Profile;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

@Slf4j
@Component
@Profile("!local")
@ConditionalOnExpression(value = "#{'${app.scheduling.mode:none}'.equals('optimized')}")
public class OptimizedProductPriceScheduler {

    private final EntityManagerFactory entityManagerFactory;

    private final BigDecimal priceIncreasePercentage;

    private final Boolean exclusiveLock;

    public OptimizedProductPriceScheduler(
            EntityManagerFactory entityManagerFactory,
            @Value("#{new java.math.BigDecimal(\"${app.scheduling.priceIncreasePercentage:10}\")}")
            BigDecimal priceIncreasePercentage,
            @Value("${app.scheduling.optimization.exclusive-lock:false}")
            Boolean exclusiveLock
    ) {
        this.entityManagerFactory = entityManagerFactory;
        this.priceIncreasePercentage = priceIncreasePercentage;
        this.exclusiveLock = exclusiveLock;
    }

    @MeasureExecutionTime
    @Scheduled(fixedRateString = "${app.scheduling.period}")
    public void increaseProductPrice() {
        log.info("Start optimized scheduling");
        final Session session = entityManagerFactory.createEntityManager().unwrap(Session.class);

        try (session) {
            session.doWork(new Work() {
                @Override
                public void execute(Connection connection) throws SQLException {
                    try (
                            BufferedWriter fileWriter = new BufferedWriter(new FileWriter("results.txt"));
                            connection
                    ) {
                        connection.setAutoCommit(false);
                        long rowCounter = 0L;

                        if (exclusiveLock) {
                            String lock = "LOCK TABLE products IN ACCESS EXCLUSIVE MODE";
                            Statement lockStatement = connection.createStatement();
                            lockStatement.execute(lock);
                        }

                        String selectQuery = "SELECT * FROM products FOR UPDATE";
                        Statement statement = connection.createStatement();

                        String updateQuery = "UPDATE products SET PRICE = ? WHERE id = ?";
                        PreparedStatement preparedStatement = connection.prepareStatement(updateQuery);

                        ResultSet rs = statement.executeQuery(selectQuery);
                        while (rs.next()) {
                            final BigDecimal newPrice = getNewPrice(rs.getBigDecimal("price"), priceIncreasePercentage);
                            preparedStatement.setBigDecimal(1, newPrice);
                            preparedStatement.setObject(2, UUID.fromString(rs.getString("id")));
                            preparedStatement.addBatch();

                            fileWriter.write(buildString(rs, rowCounter, newPrice));
                            fileWriter.newLine();

                            rowCounter++;
                            if (rowCounter % 100000 == 0) {
                                preparedStatement.executeBatch();
                                log.debug("Rows updated: " + rowCounter);
                            }
                        }
                        preparedStatement.executeBatch();

                        log.debug("Committing");
                        connection.commit();
                    } catch (Exception e) {
                        connection.rollback();
                        throw new RuntimeException(e);
                    }
                }
            });
        }
        log.info("End optimized scheduling");
    }

//        session.beginTransaction();
//        Query<ProductEntity> query = session.createNativeQuery("select * from products FOR UPDATE", ProductEntity.class);
//        ScrollableResults<ProductEntity> results = query.scroll();
//        while (results.next()) {
//            ProductEntity product = results.get();
//            BigDecimal currentPrice = product.getPrice();
//            BigDecimal newPrice = currentPrice.multiply(BigDecimal.ONE.add(priceIncreasePercentage.divide(BigDecimal.valueOf(100))));
//            product.setPrice(newPrice.setScale(2, RoundingMode.HALF_UP));
//
//        }
//        session.getTransaction().commit();
//        session.close();

    private BigDecimal getNewPrice(BigDecimal oldPrice, BigDecimal increase) {
        return oldPrice.multiply(BigDecimal.ONE.add(increase.divide(BigDecimal.valueOf(100), 4, RoundingMode.HALF_UP)));
    }

    private String buildString(ResultSet resultSet, Long counter, BigDecimal newPrice) throws SQLException {
        final StringBuilder builder = new StringBuilder();
        builder.append(counter);
        builder.append(" ");
        builder.append(resultSet.getString("id"));
        builder.append(" ");
        builder.append(resultSet.getString("name"));
        builder.append(" ");
        builder.append(resultSet.getString("description"));
        builder.append(" ");
        builder.append(newPrice);
        builder.append(" ");
        builder.append(resultSet.getString("article"));

        return builder.toString();
    }
}
```

2024-04-29 12:43 UTC, merged