Task2: add multi-criteria search
NikitinNikita94/wareshop pull request #5
Opened 2024-04-25 21:11 UTC by NikitinNikita94

— Использовать criteria api + springdata.
— Микросервис должен возвращать данные из бд, основываясь на запрошенных критериях. Все критерии объединяются по "И" между собой.
— В теле запроса может быть много критериев, в том числе по одному и тому же полю, как например "price" в json выше.
— Операцию нужно передавать в виде символа (= >= <= ~) или слова EQUAL, GRATER_THAN_OR_EQ, LESS_THAN_OR_EQ, LIKE.
— Валидация должна работать.
— Необходимо, чтобы при добавлении нового поля в таблицу приходилось делать минимум доработок для поддержки реализованного функционала.

2024-04-27 11:49 UTC, GUR-ok requested changes
В целом ок, главное логику вынести из контроллера.

2024-04-27 11:49 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/controller/rest/ProductRestController.java
> +        ProductSpecificationBuilder builder = new ProductSpecificationBuilder();
в контроллере не должно быть логики. вызываем сервис и логику туда

2024-04-27 11:49 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/entity/response/APIResponse.java
> +public record APIResponse(
Кажется это лишнее

2024-04-27 11:49 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/controller/rest/ProductRestController.java
> +        return new ResponseEntity<>(apiResponse, apiResponse.responseCode());
два раза код передаем

2024-04-27 11:49 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/search/criteria/SearchCriteriaDto.java
> +public class SearchCriteriaDto<T> {
Можно было не заворачивать в еще одну дто, в контролле просто писком принять

2024-04-27 11:49 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/search/criteria/SearchOperation.java
> +            case "=" -> EQUAL;
а в таком случае словом получится принять?

2024-04-27 11:49 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/search/specification/ProductSpecification.java
> +    private final SearchCriteria searchCriteria;
может тут сразу списком и сразу из всего списка соберем спецификацию? тогда  ProductSpecificationBuilder как будто не нужен

2024-04-27 11:49 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/search/specification/ProductSpecificationBuilder.java
> +        for (int idx = 1; idx < params.size(); idx++) {
можно не по индексам, а просто foreach
```
for (type itVar : array)
{
    Блок операторов;
}
```

2024-04-27 11:49 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/controller/rest/ProductRestController.java
> +        APIResponse apiResponse = APIResponse.builder()
кажется достаточно возвращать ```return new ResponseEntity<>(productDtoInfos, HttpStatus.OK);```
или ```return ResponseEntity.ok().body(productDtoInfos);```

2024-04-29 12:47 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/search/criteria/SearchOperation.java
> +            case "=" -> EQUAL;
Не учел,переделал!

2024-04-29 12:48 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/search/specification/ProductSpecification.java
> +    private final SearchCriteria searchCriteria;
Убрал ProductSpecificationBuilder , логику перенес в один класс!

2024-04-29 12:49 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/controller/rest/ProductRestController.java
> +        APIResponse apiResponse = APIResponse.builder()
Выбрал второй вариант.

2024-05-01 11:12 UTC, GUR-ok approved these changes
Вроде ок. Можно мержить со сквошем. Прошлый мр смержил без моего апрува. В принципе не страшно, но вроде договаривались без моего апрува не мержить.

2024-05-05 09:20 UTC, merged