Task4: custom products
NikitinNikita94/wareshop pull request #7
Opened 2024-05-09 16:20 UTC by NikitinNikita94

- скрин диаграммы связей 
![Снимок экрана от 2024-05-09 15-10-22](https://github.com/NikitinNikita94/wareshop/assets/69115229/ab296f96-156b-42f9-886c-a4609e2cd704)

а) Выполнить отдельным скриптом миграции:
- Таблица product - переименовать в ед. числе
- Добавить новую колонку is_available - boolean, not null

б) Выполнить отдельным скриптом миграции:
- Создать таблицу order - таблица заказов
Колонки:
id -uuid, pk
customer_id - bigint,not null
status - varchar, not null
delivery_address - varchar, not null

Статусы заказа, енум:
  CREATED,
  CONFIRMED,
      CANCELLED,
      DONE,
      REJECTED,

в) Выполнить отдельным скриптом миграции:
- Создать таблицу customer
Колонки:
id - bigint, pk, sequence
login - varchar, констрейнт уникальности, not null
email - varchar, not null
is_active - boolean, not null 

г) Продумать какие еще таблицы и связи нужны для хранения цены и количества заказанных товаров. Создать отдельным скриптом миграции.

д) Сделать скрин визуализации отношений в таблицах (ERD) 
DBeaver 21.2.4 забагованный. лучше установить 22.0.2+ или использовать ultimate idea 

е) Разработать эндпоинты:  
1. POST /order создание заказа
customerId взять из headers

  
  {
    "deliveryAddress": "string",
    "products" : [
      {
        "id": "98a125c3-a5e8-4e1d-81eb-7e57bff69e47",
        "quantity": 2
      }
    ]
  }

- наличие товара на складе (таблица product)
- цена товара при создании заказа фиксируется
- количество на складе должно уменьшатся
- добавить в заказ можно только доступный к заказу товар
- начальный статус CREATED

2. PATCH /order/{orderId}
customerId взять из headers, возвращать 403, если пользователь хочет изменить не свой заказ

добавление товара в заказ. Можно добавить товар только в CREATED

[
  {
    "id": "98a125c3-a5e8-4e1d-81eb-7e57bff69e47",
    "quantity": 1
  },
  {
    "id": "12a100c3-a5e8-4e1d-81eb-7e57bff69e1",
    "quantity": 10
  }
]

- цена фиксируется заново для добавленного товара
- N+1 пофиксить и на нее посмотреть при findById

3.  GET /order/{orderId} 
customerId взять из headers, возвращать 403, если пользователь хочет получить не свой заказ

- получить заказ пользователя

ответ вида:

{  
  "orderId": "uuid",
  "products": [
    "productId": "98a125c3-a5e8-4e1d-81eb-7e57bff69e47",
    "name": "string", - из таблицы Product
    "quantity": 20.0 - количество из ЗАКАЗА
    "price": 5.0 - цена товара в ЗАКАЗА
  ],
  "totalPrice": 100.0 - общая стоимость ВСЕХ товаров в заказе (можно и в бд хранить, можно динамически)
}  

- products получить проекцией

4. DELETE /order/{orderId} - soft delete. Проставляем статус CANCELLED. не во всех статусах можно удалить, только в CREATED.
customerId взять из headers, возвращать 403, если пользователь хочет удалить не свой заказ

- товары удаленного (отмененного) заказа возвращаются на склад
- n+1 - не грузить вложенные коллекции, если получится

5. POST /order/{orderId}/confirm
customerId взять из headers

- сервисный метод не делает ничего, оставить todo

6. PATCH /order/{orderId}/status - изменение статуса для back-2-back взаимодействия 
{
  "status": "DONE"
}

2024-05-12 09:04 UTC, GUR-ok requested changes

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/entity/Order.java
> +    @Fetch(FetchMode.SUBSELECT)
а что будет с третьим уровнем вложенности? Ты получишь первым запросом ордер, вторым сабселектом OrderItem. А что делать с товарами? Предполагаю, что лишние селект продукты. Проверить в методе на апдейт числа товаров. Предлагаю убрать здесь fetch. А получать все три уровня вложенности через метод жпа репозитория
```
    @Query("""
                select o from OrderEntity o
                left join fetch o.orderedProducts ps
                left join fetch ps.product p
                where o.id = :orderId
           """)
    Optional<OrderEntity> findByIdFetchOrderedProducts(UUID orderId);
```

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/entity/Order.java
> +    @OneToMany(mappedBy = "pk.order", fetch = FetchType.LAZY)
добавить каскадность придется, иначе при сохранении OrderItems будут лишние запросы (см. чат)

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/entity/OrderItem.java
> +
Сюда нужно добавлять и OrderEntity и ProductEntity, чтобы получать все сразу одним запросом

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/controller/rest/OrderRestController.java
> +    public ResponseEntity<OrderDtoIfo> updateOrder(@RequestHeader(value = "customerId") long customerId,
Зачем все заворачивать в  ResponseEntity?

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/controller/rest/OrderRestController.java
> +    public ResponseEntity<?> delete(@RequestHeader(value = "customerId") long customerId,
void

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/controller/rest/OrderRestController.java
> +    public ResponseEntity<OrderDtoIfo> createOrderConfirm(@RequestHeader(value = "customerId") long customerId) {
Зачем везде возвращать OrderDtoIfo? везде uuid или void где создаешь, апдейтишь, меняешь статус

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/service/OrderService.java
> +        return orderMapper.toReadOrderDto(saveOrder);
скинь пожалуйста скрин логово запросов хибернейта

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/service/OrderService.java
> +                addOrderItem(productRepository.getReferenceById(product.productId()), saveOrder, product.quantity()));
Тут селекты по каждому айди. нужно одним запрсоом все получить.
Алгоритм
1. Проверили кастомера, что он есть, если нет исключение
2. Находим все товары из запроса по айди одним селектом через findByIdIn, делаем из этого хэшмапу productId -> productEntity
3. Создаем предварительно orderEntity, чтобы его сеттить в orderedProduct
4. По данным товаров из запроса проходимся стримом и собираем OrderedProduct, используя хэшмапу из шага два. Тут же проверяем количество и isAvailable
5. Сеттим в ордер эти товары. и сохраняемся каскадно, засейвив только ордер

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/service/OrderService.java
> +                        addOrderItem(productRepository.getReferenceById(product.productId()), order, product.quantity());
тут тоже нужно сходить 1 раз за всеми товарами по пачке айди.
Алгоритм
1. Получаем ордер со всеми потрохами одним запросом. Проверяем статус и кастомера.
2. Находим все товары из запроса по айди одним селектом через findByIdIn, делаем из этого хэшмапу productId -> productEntity
3. По данным товаров из запроса проходимся стримом и собираем новый OrderedProduct или апдейтим старый, используя хэшмапу из шага два. Потребуется определять, есть ли товар уже в заказе, возможно сделать еще одну мапу. Тут же проверяем количество и isAvailable
4. Сохраняем ордер каскадно сохраняется все остальное

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/service/OrderService.java
> +                    if (customerId != order.getCustomer().getId()) {
order.getCustomer().getId() даст лишний запрос?
 Мб поставим     @Fetch(FetchMode.JOIN) ?

2024-05-12 09:04 UTC, GUR-ok commented on src/main/java/team/mediasoft/wareshop/service/OrderService.java
> +                    if (!productRepository.existsByAmountIsGreaterThanEqual(product.quantity())) {
тут тьма лишний запросов в бд

2024-05-12 10:16 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/service/OrderService.java
> +        return orderMapper.toReadOrderDto(saveOrder);
![Снимок экрана от 2024-05-12 12-15-40](https://github.com/NikitinNikita94/wareshop/assets/69115229/908ee022-692b-45d2-893a-9a22b00e958d)

2024-05-12 10:34 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/controller/rest/OrderRestController.java
> +    public ResponseEntity<OrderDtoIfo> updateOrder(@RequestHeader(value = "customerId") long customerId,
До таск3 не знал, спринг сам в респонсЕнтити заворачивает!
Исправлю.

2024-05-12 10:37 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/controller/rest/OrderRestController.java
> +    public ResponseEntity<OrderDtoIfo> createOrderConfirm(@RequestHeader(value = "customerId") long customerId) {
В продуктовом контроллере из тех же методов возвращали сущность,Но теперь на будущие учту.
Переделаю.

2024-05-12 10:42 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/service/OrderService.java
> +                    if (customerId != order.getCustomer().getId()) {
При findById сразу сущность достается c Customer, это при getReferenceById у нас Lazy.
Но все равно поправлю!

2024-05-12 10:56 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/service/OrderService.java
> +                    if (customerId != order.getCustomer().getId()) {
![Снимок экрана от 2024-05-12 12-55-33](https://github.com/NikitinNikita94/wareshop/assets/69115229/7ec9507f-ff1c-4b20-b0ec-da0ef5d1eb92)
findOrderById method

2024-05-12 17:08 UTC, NikitinNikita94 commented on src/main/java/team/mediasoft/wareshop/service/OrderService.java
> +        return orderMapper.toReadOrderDto(saveOrder);
По сравнению с верхним запросом, небо и земля)
![Снимок экрана от 2024-05-12 19-05-17](https://github.com/NikitinNikita94/wareshop/assets/69115229/896353e7-9fb0-424f-918c-a54cde5437d1)

Спасибо Юрий ЗА ВАШ ТРУД!!!

2024-05-22 10:16 UTC, GUR-ok approved these changes
Ставь пожалуйста лайки на мои комменты, которые поправлены в след.раз. Тут вроде ок, давай помержим со сквошем =)

2024-05-24 19:19 UTC, merged